root: true

plugins:
  - functional
  - prettier

extends:
  - airbnb
  - 'plugin:functional/external-recommended'
  - 'plugin:functional/recommended'
  - plugin:prettier/recommended

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    node: { 'paths': ['src'] }

rules:
  import/extensions: 0
  import/prefer-default-export: 'off'
  import/no-extraneous-dependencies: ['error', { 'devDependencies': true }]
  react/prop-types: 0
  react/react-in-jsx-scope: 'off'
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/jsx-props-no-spreading: 0
  no-console: 0
  no-shadow: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  functional/no-class: 0
  functional/no-this-expression: 0
  jsx-a11y/label-has-associated-control: 0
  class-methods-use-this: 0
